# Usar Usuario, Clave y Base de Datos con su propia información, por ejemplo:
# POSTGRES_USER: gonzalezj       --->>> su apellido más la primera letra de su nombre
# POSTGRES_PASSWORD: Jesus556    --->>> una clave que ud. elija
# POSTGRES_DB: Prueba            --->>> la Base de Datos deberá tener el nombre de Prueba 

version: ''

services:
  mysql:
    image: mysql  # Usa la versión de MySQL que prefieras
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root   # Cambia la contraseña del root
      MYSQL_DATABASE: ejemplo           # Nombre de una base de datos inicial
      MYSQL_USER: angel2244               # Nombre de usuario
      MYSQL_PASSWORD: Angel2244       # Contraseña del usuario
    volumes:
      - mysql_data:/var/lib/mysql  # Monta el volumen para persistir los datos
    ports:
      - "3306:3306"  # Expone el puerto de MySQL
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql  # Nombre del servicio de MySQL (debe coincidir con el de arriba)
      MYSQL_ROOT_PASSWORD: root # Mismo root password definido antes
    ports:
      - "8080:80"  # Expone el puerto 8080 para acceder a phpMyAdmin
    depends_on:
      - mysql  # Asegura que phpMyAdmin se inicie después de MySQL
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge